# Generated by Django 4.1.7 on 2023-02-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Skin name')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Skin photo')),
                ('price', models.IntegerField(verbose_name='Skin price')),
                ('float', models.FloatField(verbose_name='Skin quality')),
                ('availability', models.BooleanField(default=True, verbose_name='Skin availability')),
                ('amount', models.IntegerField(verbose_name='Skin amount')),
                ('amount_likes', models.IntegerField(verbose_name='Skin like')),
                ('amount_dislikes', models.IntegerField(verbose_name='Skin dislike')),
                ('amount_orders', models.IntegerField(verbose_name='Skin orders')),
                ('pattern', models.IntegerField(verbose_name='Skin pattern')),
                ('appearance', models.CharField(choices=[('Factory New', 'Factory New'), ('Minimal Wear', 'Minimal Wear'), ('Field-Tested', 'Field-Tested'), ('Well-Worn', 'Well-Worn'), ('Battle-Scarred', 'Battle-Scarred')], max_length=255, verbose_name='Skin quality')),
                ('is_stattrak', models.BooleanField(default=False, verbose_name='Skin is StatTrak')),
                ('category', models.CharField(choices=[('Knife', (('Bayonet', 'Bayonet'), ('Bowie', 'Bowie'), ('Butterfly', 'Butterfly'), ('Falchion', 'Falchion'), ('Flip', 'Flip'), ('Gut', 'Gut'), ('Huntsman', 'Huntsman'), ('Karambit', 'Karambit'), ('M9 Bayonet', 'M9 Bayonet'), ('Navaja', 'Navaja'), ('Shadow Daggers', 'Shadow Daggers'), ('Stiletto', 'Stiletto'), ('Talon', 'Talon'), ('Ursus', 'Ursus'), ('Classic', 'Classic'), ('Skeleton', 'Skeleton'), ('Nomad', 'Nomad'), ('Survival', 'Survival'), ('Paracord', 'Paracord'))), ('Gloves', (('Bloodhound', 'Bloodhound'), ('Driver', 'Driver'), ('Hand Wraps', 'Hand Wraps'), ('Hydra', 'Hydra'), ('Moto', 'Moto'), ('Specialist', 'Specialist'), ('Sport', 'Sport'))), ('Pistols', (('CZ75-Auto', 'CZ75-Auto'), ('Desert Eagle', 'Desert Eagle'), ('Dual Berettas', 'Dual Berettas'), ('Five-SeveN', 'Five-SeveN'), ('Glock-18', 'Glock-18'), ('P2000', 'P2000'), ('P250', 'P250'), ('R8 Revolver', 'R8 Revolver'), ('Tec-9', 'Tec-9'), ('USP-S', 'USP-S'))), ('Sub-Machine Guns', (('MAC-10', 'MAC-10'), ('MP5-SD', 'MP5-SD'), ('MP7', 'MP7'), ('MP9', 'MP9'), ('P90', 'P90'), ('PP-Bizon', 'PP-Bizon'), ('UMP-45', 'UMP-45'))), ('Assault Rifles', (('AK-47', 'AK-47'), ('AUG', 'AUG'), ('FAMAS', 'FAMAS'), ('Galil AR', 'Galil AR'), ('M4A1-S', 'M4A1-S'), ('M4A4', 'M4A4'), ('SG 553', 'SG 553'))), ('Sniper Rifles', (('AWP', 'AWP'), ('G3SG1', 'G3SG1'), ('SCAR-20', 'SCAR-20'), ('SSG 08', 'SSG 08'))), ('Shotguns', (('MAG-7', 'MAG-7'), ('Nova', 'Nova'), ('Sawed-Off', 'Sawed-Off'), ('XM1014', 'XM1014'))), ('Machine Guns', (('M249', 'M249'), ('Negev', 'Negev'))), ('Keys', 'Keys'), ('Other', (('Sticker', 'Sticker'), ('Case', 'Case'), ('Graffiti', 'Graffiti'), ('Music', 'Music'), ('Badge', 'Badge'), ('Agents', 'Agents'), ('Patch', 'Patch')))], max_length=200, verbose_name='Skin Category')),
                ('quality', models.CharField(choices=[('Consumer Grade', 'Consumer Grade'), ('Industrial Grade', 'Industrial Grade'), ('Mil-Spec Grade', 'Mil-Spec Grade'), ('Restricted', 'Restricted'), ('Classified', 'Classified'), ('Covert', 'Covert')], max_length=200, verbose_name='Skin quality')),
            ],
            options={
                'verbose_name': 'Skin',
                'verbose_name_plural': 'Skins',
            },
        ),
    ]
