# Generated by Django 4.1.7 on 2023-02-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skins',
            old_name='is_stattrak',
            new_name='is_stattrack',
        ),
        migrations.AlterField(
            model_name='skins',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Skin amount'),
        ),
        migrations.AlterField(
            model_name='skins',
            name='amount_dislikes',
            field=models.IntegerField(default=0, verbose_name='Skin dislike'),
        ),
        migrations.AlterField(
            model_name='skins',
            name='amount_likes',
            field=models.IntegerField(default=0, verbose_name='Skin like'),
        ),
        migrations.AlterField(
            model_name='skins',
            name='amount_orders',
            field=models.IntegerField(default=0, verbose_name='Skin orders'),
        ),
        migrations.AlterField(
            model_name='skins',
            name='appearance',
            field=models.CharField(choices=[('Factory-New', 'Factory-New'), ('Minimal-Wear', 'Minimal-Wear'), ('Field-Tested', 'Field-Tested'), ('Well-Worn', 'Well-Worn'), ('Battle-Scarred', 'Battle-Scarred')], max_length=255, verbose_name='Skin type'),
        ),
        migrations.AlterField(
            model_name='skins',
            name='category',
            field=models.CharField(choices=[('Knife', (('Bayonet', 'Bayonet'), ('Bowie', 'Bowie'), ('Butterfly', 'Butterfly'), ('Falchion', 'Falchion'), ('Flip', 'Flip'), ('Gut', 'Gut'), ('Huntsman', 'Huntsman'), ('Karambit', 'Karambit'), ('M9-Bayonet', 'M9-Bayonet'), ('Navaja', 'Navaja'), ('Shadow-Daggers', 'Shadow-Daggers'), ('Stiletto', 'Stiletto'), ('Talon', 'Talon'), ('Ursus', 'Ursus'), ('Classic', 'Classic'), ('Skeleton', 'Skeleton'), ('Nomad', 'Nomad'), ('Survival', 'Survival'), ('Paracord', 'Paracord'))), ('Gloves', (('Bloodhound', 'Bloodhound'), ('Driver', 'Driver'), ('Hand-Wraps', 'Hand-Wraps'), ('Hydra', 'Hydra'), ('Moto', 'Moto'), ('Specialist', 'Specialist'), ('Sport', 'Sport'))), ('Pistols', (('CZ75-Auto', 'CZ75-Auto'), ('Desert-Eagle', 'Desert-Eagle'), ('Dual-Berettas', 'Dual-Berettas'), ('Five-SeveN', 'Five-SeveN'), ('Glock-18', 'Glock-18'), ('P2000', 'P2000'), ('P250', 'P250'), ('R8-Revolver', 'R8-Revolver'), ('Tec-9', 'Tec-9'), ('USP-S', 'USP-S'))), ('Sub-Machine Guns', (('MAC-10', 'MAC-10'), ('MP5-SD', 'MP5-SD'), ('MP7', 'MP7'), ('MP9', 'MP9'), ('P90', 'P90'), ('PP-Bizon', 'PP-Bizon'), ('UMP-45', 'UMP-45'))), ('Assault Rifles', (('AK-47', 'AK-47'), ('AUG', 'AUG'), ('FAMAS', 'FAMAS'), ('Galil-AR', 'Galil-AR'), ('M4A1-S', 'M4A1-S'), ('M4A4', 'M4A4'), ('SG-553', 'SG-553'))), ('Sniper Rifles', (('AWP', 'AWP'), ('G3SG1', 'G3SG1'), ('SCAR-20', 'SCAR-20'), ('SSG-08', 'SSG-08'))), ('Shotguns', (('MAG-7', 'MAG-7'), ('Nova', 'Nova'), ('Sawed-Off', 'Sawed-Off'), ('XM1014', 'XM1014'))), ('Machine Guns', (('M249', 'M249'), ('Negev', 'Negev'))), ('Keys', 'Keys'), ('Other', (('Sticker', 'Sticker'), ('Case', 'Case'), ('Graffiti', 'Graffiti'), ('Music', 'Music'), ('Badge', 'Badge'), ('Agents', 'Agents'), ('Patch', 'Patch')))], max_length=200, verbose_name='Skin category'),
        ),
        migrations.AlterField(
            model_name='skins',
            name='float',
            field=models.FloatField(verbose_name='Skin float'),
        ),
        migrations.AlterField(
            model_name='skins',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Skin photo'),
        ),
        migrations.AlterField(
            model_name='skins',
            name='quality',
            field=models.CharField(choices=[('Consumer-Grade', 'Consumer-Grade'), ('Industrial-Grade', 'Industrial-Grade'), ('Mil-Spec-Grade', 'Mil-Spec-Grade'), ('Restricted', 'Restricted'), ('Classified', 'Classified'), ('Covert', 'Covert')], max_length=200, verbose_name='Skin quality'),
        ),
    ]
