# Generated by Django 4.1.7 on 2023-02-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_is_stattrak_skins_is_stattrack_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skins',
            old_name='is_stattrack',
            new_name='is_stattrak',
        ),
    ]
